// Frontend/src/app/pages/HistoryPage.tsx
import { useState, useMemo, Fragment } from 'react';
import { Search, Download, ChevronDown, ChevronUp } from 'lucide-react';
import { useInspections } from '../hooks/useInspections';
import { useParts } from '../hooks/useParts';

export function HistoryPage() {
  const inspections = useInspections(1000);
  const parts = useParts();
  const inspectionResults = inspections.data;
  const partTypes = parts.data;
  const loading = inspections.loading || parts.loading;
  const error = inspections.error || parts.error;
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState<'all' | 'OK' | 'NG'>('all');
  const [partFilter, setPartFilter] = useState('all');
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [page, setPage] = useState(1);
  const perPage = 15;

  const filtered = useMemo(() => {
    return inspectionResults.filter((r) => {
      if (statusFilter !== 'all' && r.status !== statusFilter) return false;
      if (partFilter !== 'all' && r.partCode !== partFilter) return false;
      if (search) {
        const q = search.toLowerCase();
        return r.id.toLowerCase().includes(q) || r.partName.toLowerCase().includes(q) || r.batchNo.toLowerCase().includes(q) || r.operatorName.toLowerCase().includes(q);
      }
      return true;
    });
  }, [inspectionResults, search, statusFilter, partFilter]);

  const totalPages = Math.ceil(filtered.length / perPage);
  const paginated = filtered.slice((page - 1) * perPage, page * perPage);

  const exportCSV = () => {
    const headers = 'ID,Part,Part Code,Batch,Status,Operator,Shift,Station,Timestamp,Confidence\n';
    const rows = filtered.map((r) =>
      `${r.id},${r.partName},${r.partCode},${r.batchNo},${r.status},${r.operatorName},${r.shift},${r.stationId},${r.timestamp},${r.confidenceScore}`
    ).join('\n');
    const blob = new Blob([headers + rows], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'inspection_report.csv';
    a.click();
  };

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1>Riwayat Inspeksi</h1>
          <p className="text-[var(--muted-foreground)] text-sm mt-1">Traceability data hasil inspeksi</p>
        </div>
        <button onClick={exportCSV} className="flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 text-sm self-start">
          <Download className="w-4 h-4" /> Export CSV
        </button>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-4 text-sm flex items-center justify-between gap-3">
          <span>{error}</span>
          <button onClick={() => { inspections.reload(); parts.reload(); }} className="px-3 py-1.5 bg-red-600 text-white rounded-lg text-xs">Coba lagi</button>
        </div>
      )}

      {loading && (
        <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4 text-sm text-[var(--muted-foreground)]">
          Memuat riwayat inspeksi dari backend...
        </div>
      )}

      {/* Filters */}
      <div className="flex flex-wrap gap-3">
        <div className="relative flex-1 min-w-[200px]">
          <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-[var(--muted-foreground)]" />
          <input
            value={search}
            onChange={(e) => { setSearch(e.target.value); setPage(1); }}
            className="w-full pl-9 pr-4 py-2 border border-[var(--border)] rounded-lg bg-[var(--card)] text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"
            placeholder="Cari ID, part, batch, operator..."
          />
        </div>
        <select
          value={statusFilter}
          onChange={(e) => { setStatusFilter(e.target.value as any); setPage(1); }}
          className="px-3 py-2 border border-[var(--border)] rounded-lg bg-[var(--card)] text-sm"
        >
          <option value="all">Semua Status</option>
          <option value="OK">OK</option>
          <option value="NG">NG</option>
        </select>
        <select
          value={partFilter}
          onChange={(e) => { setPartFilter(e.target.value); setPage(1); }}
          className="px-3 py-2 border border-[var(--border)] rounded-lg bg-[var(--card)] text-sm"
        >
          <option value="all">Semua Part</option>
          {partTypes.map((pt) => <option key={pt.id} value={pt.partCode}>{pt.partName}</option>)}
        </select>
      </div>

      <div className="text-sm text-[var(--muted-foreground)]">{filtered.length} hasil ditemukan</div>

      {/* Table */}
      <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-[var(--accent)]">
              <tr className="text-left">
                <th className="px-4 py-3">ID</th>
                <th className="px-4 py-3">Part</th>
                <th className="px-4 py-3">Batch</th>
                <th className="px-4 py-3">Status</th>
                <th className="px-4 py-3">Confidence</th>
                <th className="px-4 py-3">Shift</th>
                <th className="px-4 py-3">Station</th>
                <th className="px-4 py-3">Waktu</th>
                <th className="px-4 py-3">Detail</th>
              </tr>
            </thead>
            <tbody>
              {paginated.map((r) => (
                <Fragment key={r.id}>
                  <tr className="border-b border-[var(--border)] hover:bg-[var(--accent)]/50">
                    <td className="px-4 py-2.5" style={{ fontWeight: 500 }}>{r.id}</td>
                    <td className="px-4 py-2.5">
                      <div>{r.partName}</div>
                      <div className="text-xs text-[var(--muted-foreground)]">{r.partCode} | {r.vendor}</div>
                    </td>
                    <td className="px-4 py-2.5">{r.batchNo}</td>
                    <td className="px-4 py-2.5">
                      <span className={`px-2 py-0.5 rounded-full text-xs ${r.status === 'OK' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}`}>{r.status}</span>
                    </td>
                    <td className="px-4 py-2.5">{r.confidenceScore}%</td>
                    <td className="px-4 py-2.5">{r.shift}</td>
                    <td className="px-4 py-2.5">{r.stationId}</td>
                    <td className="px-4 py-2.5 text-xs">{new Date(r.timestamp).toLocaleString('id-ID')}</td>
                    <td className="px-4 py-2.5">
                      <button onClick={() => setExpandedId(expandedId === r.id ? null : r.id)} className="p-1 hover:bg-[var(--accent)] rounded">
                        {expandedId === r.id ? <ChevronUp className="w-4 h-4" /> : <ChevronDown className="w-4 h-4" />}
                      </button>
                    </td>
                  </tr>
                  {expandedId === r.id && (
                    <tr>
                      <td colSpan={9} className="px-4 py-3 bg-[var(--accent)]">
                        <div className="text-xs" style={{ fontWeight: 500 }}>Detail Pengukuran - Operator: {r.operatorName}</div>
                        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-2 mt-2">
                          {r.measurements.map((m) => (
                            <div key={m.dimensionName} className={`p-2 rounded border ${m.status === 'OK' ? 'border-green-200 bg-green-50' : 'border-red-200 bg-red-50'}`}>
                              <div className="text-xs text-[var(--muted-foreground)]">{m.dimensionName}</div>
                              <div className="text-sm" style={{ fontWeight: 500 }}>
                                <span className={m.status === 'OK' ? 'text-green-700' : 'text-red-700'}>{m.measured} {m.unit}</span>
                              </div>
                              <div className="text-[10px] text-[var(--muted-foreground)]">
                                Nominal: {m.nominal} | Range: {m.lowerLimit} ~ {m.upperLimit}
                              </div>
                            </div>
                          ))}
                        </div>
                      </td>
                    </tr>
                  )}
                </Fragment>
              ))}
              {!loading && paginated.length === 0 && (
                <tr>
                  <td colSpan={9} className="px-4 py-12 text-center text-[var(--muted-foreground)]">
                    {inspectionResults.length === 0 ? 'Belum ada data inspeksi dari backend.' : 'Tidak ada data yang cocok dengan filter.'}
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      {/* Pagination */}
      {totalPages > 1 && (
        <div className="flex items-center justify-center gap-2">
          <button disabled={page <= 1} onClick={() => setPage(page - 1)} className="px-3 py-1.5 border border-[var(--border)] rounded-lg text-sm disabled:opacity-50">Prev</button>
          <span className="text-sm text-[var(--muted-foreground)]">{page} / {totalPages}</span>
          <button disabled={page >= totalPages} onClick={() => setPage(page + 1)} className="px-3 py-1.5 border border-[var(--border)] rounded-lg text-sm disabled:opacity-50">Next</button>
        </div>
      )}
    </div>
  );
}

// frontend/src/routes/HistoryPage.svelte
<script lang="ts">
  import { Search, Download, ChevronDown, ChevronUp } from 'lucide-svelte';
  import { useInspections } from '$lib/hooks/useInspections.svelte';
  import { useParts } from '$lib/hooks/useParts.svelte';
  import FrameThumbnail from '$lib/components/FrameThumbnail.svelte';
  import { api, getErrorMessage } from '$lib/services/api';

  const inspections = useInspections(200);
  const parts = useParts();

  let search = $state('');
  let statusFilter = $state<'all' | 'OK' | 'NG'>('all');
  let partFilter = $state('all');
  let expandedId = $state<string | null>(null);

  let detailLoading = $state<Record<string, boolean>>({});
  let detailErrors = $state<Record<string, string>>({});
  let details = $state<Record<string, any>>({});

  const toggleExpand = async (id: string) => {
    if (expandedId === id) {
      expandedId = null;
      return;
    }

    expandedId = id;
    if (!details[id] && !detailLoading[id]) {
      detailLoading[id] = true;
      detailErrors[id] = '';
      try {
        const data = await api.getInspectionDetail(id);
        details[id] = data;
      } catch (err) {
        detailErrors[id] = getErrorMessage(err);
      } finally {
        detailLoading[id] = false;
      }
    }
  };
  let page = $state(1);
  const perPage = 15;

  const loading = $derived(inspections.loading || parts.loading);
  const error = $derived(inspections.error || parts.error);

  const filtered = $derived.by(() => {
    const q = search.toLowerCase();
    return inspections.data.filter((row) => {
      if (statusFilter !== 'all' && row.status !== statusFilter) return false;
      if (partFilter !== 'all' && row.partCode !== partFilter) return false;
      if (q) {
        return row.id.toLowerCase().includes(q)
          || row.partName.toLowerCase().includes(q)
          || row.operatorName.toLowerCase().includes(q);
      }
      return true;
    });
  });

  const totalPages = $derived(Math.max(1, Math.ceil(filtered.length / perPage)));
  const currentPage = $derived(Math.min(page, totalPages));
  const paginated = $derived(filtered.slice((currentPage - 1) * perPage, currentPage * perPage));

  const csvField = (value: unknown): string => {
    const text = value == null ? '' : String(value);
    return /[",\r\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
  };

  const exportCSV = () => {
    const headers = ['ID', 'Part', 'Part Code', 'Status', 'Operator', 'Station', 'Timestamp', 'Confidence', 'FrameUrl'];
    const lines = [headers.map(csvField).join(',')];
    for (const r of filtered) {
      lines.push([
        r.id, r.partName, r.partCode, r.status, r.operatorName, r.stationId,
        r.timestamp, r.confidenceScore, r.frameUrl ?? '',
      ].map(csvField).join(','));
    }
    const blob = new Blob(['\uFEFF', lines.join('\r\n')], { type: 'text/csv;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'inspection_report.csv';
    a.click();
    URL.revokeObjectURL(url);
  };

  const retry = () => {
    inspections.reload();
    parts.reload();
  };

  const onSearchInput = (event: Event) => {
    search = (event.currentTarget as HTMLInputElement).value;
    page = 1;
  };
  const onStatusChange = (event: Event) => {
    statusFilter = (event.currentTarget as HTMLSelectElement).value as 'all' | 'OK' | 'NG';
    page = 1;
  };
  const onPartChange = (event: Event) => {
    partFilter = (event.currentTarget as HTMLSelectElement).value;
    page = 1;
  };
  const goToPreviousPage = () => {
    page = Math.max(1, currentPage - 1);
  };
  const goToNextPage = () => {
    page = Math.min(totalPages, currentPage + 1);
  };
</script>

<div class="space-y-6 select-none font-sans">
  <!-- Title Header -->
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
    <div>
      <h1 class="text-slate-900 dark:text-white tracking-tight">Riwayat Inspeksi</h1>
      <p class="text-[var(--muted-foreground)] text-sm mt-1.5 font-medium">Traceability data dan hasil ukur historis untuk analisis kualitas berlanjut.</p>
    </div>
    <button 
      onclick={exportCSV} 
      class="inline-flex items-center justify-center gap-2 px-4.5 py-2.5 bg-gradient-to-r from-indigo-500 to-violet-600 hover:from-indigo-600 hover:to-violet-700 text-white rounded-xl text-xs font-bold shadow-md shadow-indigo-500/10 active:scale-[0.98] transition-premium self-start sm:self-auto"
    >
      <Download class="w-4 h-4" /> Export CSV
    </button>
  </div>

  {#if error}
    <div class="bg-red-500/10 border border-red-500/20 text-red-700 dark:text-red-400 rounded-2xl p-4.5 text-sm flex items-center justify-between gap-4">
      <span>{error}</span>
      <button onclick={retry} class="px-3.5 py-1.5 bg-red-600 text-white rounded-xl text-xs font-bold">Coba lagi</button>
    </div>
  {/if}

  {#if loading}
    <div class="bg-[var(--card)] border border-[var(--border)] rounded-2xl p-4 text-xs font-bold text-[var(--muted-foreground)] shadow-sm animate-pulse flex items-center gap-2">
      <span class="w-4 h-4 rounded-full border-2 border-[var(--muted-foreground)]/30 border-t-[var(--muted-foreground)] animate-spin"></span>
      <span>Memuat arsip riwayat data...</span>
    </div>
  {/if}

  <!-- Search & Filter Controls -->
  <div class="flex flex-wrap items-center gap-3">
    <div class="relative flex-1 min-w-[240px]">
      <Search class="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
      <input
        value={search}
        oninput={onSearchInput}
        class="input pl-10 pr-4 py-2.5"
        placeholder="Cari ID, nama part, operator..."
      />
    </div>
    <select value={statusFilter} onchange={onStatusChange} class="input min-w-[130px] w-auto py-2.5 px-3">
      <option value="all">Semua Status</option>
      <option value="OK">OK</option>
      <option value="NG">NG</option>
    </select>
    <select value={partFilter} onchange={onPartChange} class="input min-w-[160px] w-auto py-2.5 px-3">
      <option value="all">Semua Jenis Part</option>
      {#each parts.data as part (part.id)}
        <option value={part.partCode}>{part.partName}</option>
      {/each}
    </select>
  </div>

  <!-- Count Stats -->
  <div class="text-xs text-[var(--muted-foreground)] font-bold tracking-wide bg-slate-100/50 dark:bg-slate-900/30 border border-[var(--border)] w-fit px-3 py-1.5 rounded-lg shadow-sm">
    Ditemukan: <span class="text-indigo-500 font-mono-data">{filtered.length}</span> baris data
  </div>

  <!-- Master Data Table -->
  <div class="bg-[var(--card)] border border-[var(--border)] rounded-2xl shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead>
          <tr class="bg-slate-50 dark:bg-slate-900/40 text-slate-700 dark:text-slate-200 border-b border-[var(--border)] text-left font-bold text-xs uppercase tracking-wider">
            <th class="px-5 py-4">Part / Kode</th>
            <th class="px-5 py-4">Status</th>
            <th class="px-5 py-4">Confidence</th>
            <th class="px-5 py-4">Waktu Pengerjaan</th>
            <th class="px-5 py-4 text-right">Detail</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-[var(--border)] text-slate-800 dark:text-slate-200">
          {#each paginated as row (row.id)}
            {@const isOK = row.status === 'OK'}
            <tr class="hover:bg-slate-50/50 dark:hover:bg-slate-900/10 transition-premium duration-150">
              <td class="px-5 py-3.5">
                <div class="font-semibold text-slate-900 dark:text-white">{row.partName}</div>
                <div class="text-[10px] text-[var(--muted-foreground)] font-semibold font-mono-data mt-1.5">Code: {row.partCode} &bull; Vendor: {row.vendor}</div>
              </td>
              <td class="px-5 py-3.5">
                <span class="inline-flex px-2.5 py-1 rounded-full text-[10px] font-extrabold tracking-wide uppercase {
                  isOK 
                    ? 'bg-emerald-500/10 border border-emerald-500/20 text-emerald-600 dark:text-emerald-400' 
                    : 'bg-rose-500/10 border border-rose-500/20 text-rose-600 dark:text-rose-400'
                }">
                  {row.status}
                </span>
              </td>
              <td class="px-5 py-3.5 font-mono-data font-bold text-xs text-slate-700 dark:text-slate-300">{row.confidenceScore}%</td>
              <td class="px-5 py-3.5 text-xs text-slate-500 dark:text-slate-400 font-semibold">{new Date(row.timestamp).toLocaleString('id-ID')}</td>
              <td class="px-5 py-3.5 text-right">
                <button 
                  onclick={() => toggleExpand(row.id)} 
                  class="p-2 border border-[var(--border)] hover:bg-[var(--accent)] hover:text-[var(--accent-foreground)] rounded-xl transition-premium shadow-sm text-slate-500 dark:text-slate-400" 
                  aria-label="Tampilkan detail"
                >
                  {#if expandedId === row.id}
                    <ChevronUp class="w-4 h-4" />
                  {:else}
                    <ChevronDown class="w-4 h-4" />
                  {/if}
                </button>
              </td>
            </tr>
            {#if expandedId === row.id}
              <tr>
                <td colspan="5" class="px-5 py-5 bg-slate-50/50 dark:bg-slate-900/20 border-t border-b border-[var(--border)]">
                  {#if detailLoading[row.id]}
                    <div class="text-xs text-[var(--muted-foreground)] font-bold py-6 text-center animate-pulse flex items-center justify-center gap-2">
                      <span class="w-3.5 h-3.5 rounded-full border-2 border-[var(--muted-foreground)]/30 border-t-[var(--muted-foreground)] animate-spin"></span>
                      <span>Menganalisis dan memuat rincian pengukuran...</span>
                    </div>
                  {:else if detailErrors[row.id]}
                    <div class="text-xs text-rose-500 font-bold py-6 text-center border border-rose-500/10 rounded-xl bg-rose-500/5">
                      Gagal memperoleh data: {detailErrors[row.id]}
                    </div>
                  {:else if details[row.id]}
                    {@const detail = details[row.id]}
                    <div class="space-y-4">
                      <!-- Operator Metadata -->
                      <div class="text-xs text-slate-700 dark:text-slate-300 font-bold border-l-2 border-indigo-500 pl-2">
                        Hasil Analisis Dimensi &bull; Operator: <span class="text-slate-950 dark:text-white">{detail.operatorName}</span>
                      </div>

                      <!-- Measurement Cards Grid -->
                      <div class="grid sm:grid-cols-2 lg:grid-cols-3 gap-3.5">
                        {#each detail.measurements as measurement (measurement.dimensionName)}
                          {@const mOK = measurement.status === 'OK'}
                          <div class="p-3.5 rounded-xl border shadow-inner transition-premium hover:-translate-y-[1px] {
                            mOK 
                              ? 'bg-emerald-500/5 border-emerald-500/10 dark:border-emerald-500/5' 
                              : 'bg-rose-500/5 border-rose-500/10 dark:border-rose-500/5'
                          }">
                            <div class="text-[10px] text-[var(--muted-foreground)] font-bold tracking-wide">{measurement.dimensionName}</div>
                            <div class="text-base font-extrabold mt-2 flex items-baseline gap-1.5 font-mono-data">
                              <span class={mOK ? 'text-emerald-600 dark:text-emerald-400' : 'text-rose-600 dark:text-rose-400'}>
                                {measurement.measured} {measurement.unit}
                              </span>
                              <span class="text-[10px] font-sans font-bold px-1.5 py-0.5 rounded uppercase {
                                mOK ? 'bg-emerald-500/10 text-emerald-600' : 'bg-rose-500/10 text-rose-600'
                              }">
                                {measurement.status}
                              </span>
                            </div>
                            <div class="text-[10px] text-[var(--muted-foreground)] font-medium mt-2 pt-2 border-t border-slate-100 dark:border-slate-800/40">
                              Nominal: <span class="text-slate-700 dark:text-slate-300">{measurement.nominal}</span> &bull; Range: <span class="text-slate-700 dark:text-slate-300">{measurement.lowerLimit} ~ {measurement.upperLimit} {measurement.unit}</span>
                            </div>
                          </div>
                        {/each}
                      </div>

                      <!-- Camera Frame and Detections Overlay -->
                      {#if detail.frameUrl}
                        <div class="mt-4 max-w-xl relative rounded-2xl overflow-hidden shadow-lg border border-[var(--border)] bg-black">
                          <FrameThumbnail eventId={detail.id} initialUrl={detail.frameUrl} className="w-full h-auto block" />
                          {#each detail.detections as detection (detection.id)}
                            <div
                              class="absolute pointer-events-none border-2 {detection.status === 'OK' ? 'border-emerald-400 bbox-ok' : 'border-rose-400 bbox-ng'}"
                              style="left: {detection.bbox.x}%; top: {detection.bbox.y}%; width: {detection.bbox.width}%; height: {detection.bbox.height}%;"
                            >
                              <span class="absolute -top-6 left-0 px-2 py-0.5 bg-slate-900/90 text-white text-[9px] font-bold rounded-lg border border-slate-700/20 whitespace-nowrap shadow-md">
                                {detection.label}
                              </span>
                            </div>
                          {/each}
                        </div>
                      {/if}
                    </div>
                  {/if}
                </td>
              </tr>
            {/if}
          {/each}
          {#if !loading && paginated.length === 0}
            <tr>
              <td colspan="5" class="px-5 py-16 text-center text-[var(--muted-foreground)] font-medium">
                {inspections.data.length === 0 ? 'Belum ada rekaman arsip data inspeksi.' : 'Tidak ditemukan baris data yang cocok dengan kriteria filter.'}
              </td>
            </tr>
          {/if}
        </tbody>
      </table>
    </div>
  </div>

  <!-- Pagination Controls -->
  {#if totalPages > 1}
    <div class="flex items-center justify-center gap-3.5 pt-4">
      <button 
        disabled={currentPage <= 1} 
        onclick={goToPreviousPage} 
        class="px-4 py-2 border border-[var(--border)] rounded-xl text-xs font-bold bg-[var(--card)] hover:bg-[var(--accent)] text-slate-700 dark:text-slate-300 disabled:opacity-50 transition-premium shadow-sm hover:shadow"
      >
        Prev
      </button>
      <span class="text-xs text-[var(--muted-foreground)] font-bold font-mono-data">
        Halaman {currentPage} / {totalPages}
      </span>
      <button 
        disabled={currentPage >= totalPages} 
        onclick={goToNextPage} 
        class="px-4 py-2 border border-[var(--border)] rounded-xl text-xs font-bold bg-[var(--card)] hover:bg-[var(--accent)] text-slate-700 dark:text-slate-300 disabled:opacity-50 transition-premium shadow-sm hover:shadow"
      >
        Next
      </button>
    </div>
  {/if}
</div>
