// Frontend/src/routes/LiveTrackingPage.svelte
<script lang="ts">
  import {
    Camera, CheckCircle, Hand, Maximize2, Minimize2, MoreVertical, Play, RefreshCcw,
    RotateCcw, StopCircle, Trash2, Video, XCircle, Zap,
  } from 'lucide-svelte';
  import { useAgents } from '$lib/hooks/useAgents.svelte';
  import { useFrameStream } from '$lib/hooks/useFrameStream.svelte';
  import { useInspections } from '$lib/hooks/useInspections.svelte';
  import { useParts } from '$lib/hooks/useParts.svelte';
  import { useStations } from '$lib/hooks/useStations.svelte';
  import { api, getErrorMessage } from '$lib/services/api';
  import type {
    AgentInfo, DimensionView, InspectionResult, ObjectDetection, StationPhase, StationStatusEvent,
  } from '$lib/types/api';

  interface MergedStation {
    stationId: string;
    online: boolean;
    running: boolean;
    fps?: number;
    phase?: StationPhase;
    activePartCode?: string;
  }

  interface StationInspectionGroup {
    latest: InspectionResult;
    detections: ObjectDetection[];
  }

  type IconComponent = typeof StopCircle;
  const PHASE_LABELS: Record<StationPhase, { text: string; tone: string; icon: IconComponent }> = {
    idle: { text: 'Idle', tone: 'bg-gray-100 text-gray-700', icon: StopCircle },
    calibrating: { text: 'Kalibrasi', tone: 'bg-amber-100 text-amber-700', icon: RefreshCcw },
    ready: { text: 'Siap', tone: 'bg-blue-100 text-blue-700', icon: Hand },
    stabilizing: { text: 'Deteksi', tone: 'bg-purple-100 text-purple-700', icon: Zap },
    locked: { text: 'Terkunci', tone: 'bg-green-100 text-green-700', icon: CheckCircle },
  };

  function mergeStations(agents: AgentInfo[], stations: StationStatusEvent[]): MergedStation[] {
    const map = new Map<string, MergedStation>();
    for (const station of stations) {
      map.set(station.stationId, {
        stationId: station.stationId,
        online: station.state === 'online',
        running: Boolean(station.running),
        fps: station.fps,
        phase: station.phase,
        activePartCode: station.activePartCode,
      });
    }
    for (const agent of agents) {
      const existing = map.get(agent.stationId);
      if (!existing) continue;
      map.set(agent.stationId, {
        stationId: agent.stationId,
        online: agent.online,
        running: agent.running,
        fps: existing.fps,
        phase: agent.online ? existing.phase : 'idle',
        activePartCode: existing.activePartCode,
      });
    }
    return [...map.values()].sort((a, b) => a.stationId.localeCompare(b.stationId));
  }

  const inspections = useInspections(40);
  const stations = useStations();
  const agents = useAgents();
  const parts = useParts();

  let busy = $state<Record<string, boolean>>({});
  let toast = $state<{ text: string; tone: 'info' | 'error' } | null>(null);
  let selectedPart = $state<Record<string, string>>({});
  let inspectionView = $state<Record<string, DimensionView>>({});
  let focusedStationId = $state<string | null>(null);
  let menuStationId = $state<string | null>(null);
  let selectedDetectionKey = $state<{ stationId: string; detectionId: string } | null>(null);
  let boxesHidden = $state(false);

  const merged = $derived(mergeStations(agents.data, stations.data));
  const visibleStations = $derived(focusedStationId ? merged.filter((s) => s.stationId === focusedStationId) : merged);
  const visibleIds = $derived(visibleStations.map((s) => s.stationId));
  const frameStream = useFrameStream(() => visibleIds);

  const latestInspections = $derived(inspections.data.slice(0, 10));
  const loading = $derived(inspections.loading || stations.loading || agents.loading || parts.loading);
  const error = $derived(inspections.error || stations.error || agents.error || parts.error);

  const latestGroupsByStation = $derived.by(() => {
    const map = new Map<string, StationInspectionGroup>();
    for (const inspection of inspections.data) {
      const group = map.get(inspection.stationId);
      if (!group) {
        map.set(inspection.stationId, { latest: inspection, detections: [...inspection.detections] });
      } else if (group.latest.timestamp === inspection.timestamp) {
        group.detections.push(...inspection.detections);
      }
    }
    return map;
  });

  const selectedDetection = $derived.by(() => {
    const key = selectedDetectionKey;
    if (!key) return null;
    const group = latestGroupsByStation.get(key.stationId);
    return group?.detections.find((item) => item.id === key.detectionId) ?? null;
  });

  let lastInspectionId = $state<string | null>(null);
  $effect(() => {
    const latest = inspections.data[0];
    if (!latest) return;
    if (latest.id === lastInspectionId) return;
    lastInspectionId = latest.id;
    boxesHidden = false;
    if (latest.detections[0]) {
      selectedDetectionKey = { stationId: latest.stationId, detectionId: latest.detections[0].id };
    } else {
      selectedDetectionKey = null;
    }
  });

  $effect(() => {
    if (parts.data.length === 0) return;
    const next = { ...selectedPart };
    let changed = false;
    for (const station of merged) {
      if (!next[station.stationId]) {
        next[station.stationId] = station.activePartCode ?? parts.data[0].partCode;
        changed = true;
      }
    }
    if (changed) selectedPart = next;
  });

  $effect(() => {
    const next = { ...inspectionView };
    let changed = false;
    for (const station of merged) {
      const partCode = selectedPart[station.stationId];
      const part = parts.data.find((item) => item.partCode === partCode);
      const hasSide = part?.dimensions.some((dim) => dim.view === 'side') ?? false;
      if (!next[station.stationId] || (!hasSide && next[station.stationId] !== 'top')) {
        next[station.stationId] = 'top';
        changed = true;
      }
    }
    if (changed) inspectionView = next;
  });

  const showToast = (text: string, tone: 'info' | 'error' = 'info') => {
    toast = { text, tone };
    window.setTimeout(() => { toast = null; }, 2800);
  };

  const runCommand = async (stationId: string, label: string, fn: () => Promise<unknown>) => {
    busy = { ...busy, [stationId]: true };
    try {
      await fn();
      showToast(`${label}: ${stationId}`);
      await agents.refresh();
    } catch (err) {
      showToast(getErrorMessage(err), 'error');
    } finally {
      busy = { ...busy, [stationId]: false };
    }
  };

  const removeStation = async (stationId: string) => {
    busy = { ...busy, [stationId]: true };
    try {
      await api.deleteStation(stationId);
      if (focusedStationId === stationId) focusedStationId = null;
      if (selectedDetectionKey?.stationId === stationId) selectedDetectionKey = null;
      menuStationId = null;
      stations.reload();
      await agents.refresh();
      showToast(`Cam dihapus dari tampilan: ${stationId}`);
    } catch (err) {
      showToast(getErrorMessage(err), 'error');
    } finally {
      busy = { ...busy, [stationId]: false };
    }
  };

  const retry = () => {
    inspections.reload();
    stations.reload();
    agents.reload();
    parts.reload();
  };

  const onlineCount = $derived(merged.filter((s) => s.online).length);
  const runningCount = $derived(merged.filter((s) => s.running).length);

  const sessionStats = $derived.by(() => {
    let total = 0, ok = 0, ng = 0;
    for (const item of latestInspections) {
      total += 1;
      if (item.status === 'OK') ok += 1;
      else if (item.status === 'NG') ng += 1;
    }
    return { total, ok, ng, ngRate: total > 0 ? ((ng / total) * 100).toFixed(1) : '0.0' };
  });

  const measurements = $derived(selectedDetection?.measurements ?? []);
  const okCount = $derived(measurements.filter((item) => item.status === 'OK').length);
  const ngCount = $derived(measurements.filter((item) => item.status !== 'OK').length);
</script>

<div class="space-y-4">
  {#if toast}
    <div class="fixed top-4 right-4 z-50 px-4 py-2.5 rounded-lg shadow-lg text-sm text-white {toast.tone === 'error' ? 'bg-red-600' : 'bg-blue-600'}">
      {toast.text}
    </div>
  {/if}

  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
    <div>
      <h1>Live Tracking</h1>
      <p class="text-[var(--muted-foreground)] text-sm mt-1">
        Streaming berjalan terus. Data masuk saat operator menekan Capture.
      </p>
    </div>
    <div class="flex flex-wrap items-center gap-2 text-xs">
      <span class="px-2 py-1 rounded-full bg-green-100 text-green-700">{onlineCount} Online</span>
      <span class="px-2 py-1 rounded-full bg-blue-100 text-blue-700">{runningCount} Running</span>
    </div>
  </div>

  {#if error}
    <div class="bg-red-50 border border-red-200 text-red-700 rounded-xl p-4 text-sm flex items-center justify-between gap-3">
      <span>{error}</span>
      <button onclick={retry} class="px-3 py-1.5 bg-red-600 text-white rounded-lg text-xs">Coba lagi</button>
    </div>
  {/if}

  <div class="grid lg:grid-cols-[1fr_360px] gap-4">
    <div class="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4">
      <div class="flex items-center justify-between mb-3">
        <h3 class="text-sm">Kamera</h3>
        <span class="text-xs text-[var(--muted-foreground)]">
          {focusedStationId ? `Focus: ${focusedStationId}` : `${merged.length} station`}
        </span>
      </div>

      {#if loading && merged.length === 0}
        <div class="grid sm:grid-cols-2 gap-3">
          {#each [0, 1] as i (i)}
            <div class="h-72 bg-[var(--accent)] rounded animate-pulse"></div>
          {/each}
        </div>
      {:else if merged.length === 0}
        <div class="text-center py-12 text-[var(--muted-foreground)]">
          <Video class="w-12 h-12 mx-auto mb-3 opacity-30" />
          <p class="text-sm">Belum ada agent yang terhubung.</p>
          <p class="text-xs mt-1">Jalankan agent di mesin local untuk mulai streaming.</p>
        </div>
      {:else}
        <div class={focusedStationId ? 'grid gap-4' : 'grid xl:grid-cols-2 gap-4'}>
          {#each visibleStations as station (station.stationId)}
            {@const frameUrl = frameStream.frames[station.stationId]}
            {@const isBusy = busy[station.stationId]}
            {@const phase = station.phase ?? (station.running ? 'ready' : 'idle')}
            {@const phaseMeta = PHASE_LABELS[phase]}
            {@const PhaseIcon = phaseMeta.icon}
            {@const partCode = selectedPart[station.stationId] ?? ''}
            {@const selectedPartType = parts.data.find((p) => p.partCode === partCode)}
            {@const activePart = parts.data.find((p) => p.partCode === station.activePartCode) ?? selectedPartType}
            {@const hasSideView = selectedPartType?.dimensions.some((d) => d.view === 'side') ?? false}
            {@const view = inspectionView[station.stationId] ?? 'top'}
            {@const latestGroup = latestGroupsByStation.get(station.stationId)}
            {@const detections = boxesHidden ? [] : (latestGroup?.detections ?? [])}

            <div class="border border-[var(--border)] rounded-lg overflow-hidden flex flex-col">
              <div class="aspect-video bg-black flex items-center justify-center relative {focusedStationId ? 'min-h-[480px]' : ''}">
                {#if station.running && frameUrl}
                  <img src={frameUrl} alt={station.stationId} class="w-full h-full object-contain" />
                {:else}
                  <div class="text-gray-500 text-xs flex flex-col items-center">
                    <Video class="w-8 h-8 mb-2 opacity-50" />
                    {station.online ? (station.running ? 'Menunggu frame...' : 'Idle - pilih part lalu klik Mulai') : 'Agent offline'}
                  </div>
                {/if}

                {#each detections as detection (detection.id)}
                  {@const selected = selectedDetectionKey?.stationId === station.stationId && selectedDetectionKey.detectionId === detection.id}
                  <button
                    onclick={(event) => {
                      event.stopPropagation();
                      selectedDetectionKey = { stationId: station.stationId, detectionId: detection.id };
                    }}
                    class="absolute bg-transparent {selected ? 'border-4 ring-2 ring-white z-20' : 'border-2 z-10'} {detection.status === 'OK' ? 'border-green-400' : 'border-red-400'}"
                    style="left: {detection.bbox.x}%; top: {detection.bbox.y}%; width: {detection.bbox.width}%; height: {detection.bbox.height}%;"
                    title={detection.label}
                    aria-label={detection.label}
                  ></button>
                {/each}

                <div class="absolute top-2 left-2 flex flex-col gap-1">
                  <span class="text-[10px] px-2 py-0.5 rounded-full {station.online ? 'bg-green-500 text-white' : 'bg-red-500 text-white'}">
                    {station.online ? 'ONLINE' : 'OFFLINE'}
                  </span>
                  {#if station.running}
                    <span class="text-[10px] px-2 py-0.5 rounded-full inline-flex items-center gap-1 {phaseMeta.tone}">
                      <PhaseIcon class="w-3 h-3" />
                      {phaseMeta.text}
                    </span>
                  {/if}
                </div>

                <div class="absolute top-2 right-2 flex items-center gap-1">
                  {#if station.fps && station.running}
                    <span class="text-[10px] bg-black/60 text-white px-2 py-1 rounded-full">{station.fps.toFixed(1)} FPS</span>
                  {/if}
                  <button
                    type="button"
                    onclick={() => focusedStationId = focusedStationId === station.stationId ? null : station.stationId}
                    title={focusedStationId === station.stationId ? 'Minimize' : 'Maximize'}
                    class="w-8 h-8 rounded-full bg-black/60 text-white inline-flex items-center justify-center hover:bg-black/80"
                  >
                    {#if focusedStationId === station.stationId}
                      <Minimize2 class="w-4 h-4" />
                    {:else}
                      <Maximize2 class="w-4 h-4" />
                    {/if}
                  </button>
                  <div class="relative">
                    <button
                      type="button"
                      onclick={() => menuStationId = menuStationId === station.stationId ? null : station.stationId}
                      title="Menu camera"
                      class="w-8 h-8 rounded-full bg-black/60 text-white inline-flex items-center justify-center hover:bg-black/80"
                    >
                      <MoreVertical class="w-4 h-4" />
                    </button>
                    {#if menuStationId === station.stationId}
                      <div class="absolute right-0 mt-2 w-48 rounded-lg border border-[var(--border)] bg-[var(--card)] shadow-lg z-30 p-1">
                        <button
                          type="button"
                          disabled={isBusy}
                          onclick={() => removeStation(station.stationId)}
                          class="w-full flex items-center gap-2 px-3 py-2 rounded-md text-left text-xs text-red-600 hover:bg-red-50 disabled:opacity-50"
                        >
                          <Trash2 class="w-4 h-4" /> Hapus dari tampilan
                        </button>
                      </div>
                    {/if}
                  </div>
                </div>
              </div>

              <div class="p-3 space-y-2.5">
                <div class="flex items-center justify-between gap-2">
                  <div class="min-w-0">
                    <div class="text-sm truncate" style="font-weight: 500">{station.stationId}</div>
                    <div class="text-[11px] text-[var(--muted-foreground)] truncate">
                      {activePart ? `${activePart.partName} - ${activePart.partCode}` : 'Belum ada part'}
                    </div>
                  </div>
                </div>

                {#if !station.running}
                  <div class="grid md:grid-cols-[1fr_140px_120px] gap-2">
                    <select
                      disabled={!station.online || isBusy || parts.data.length === 0}
                      value={partCode}
                      onchange={(event) => selectedPart = { ...selectedPart, [station.stationId]: (event.currentTarget as HTMLSelectElement).value }}
                      class="flex-1 min-w-0 px-2.5 py-1.5 text-xs border border-[var(--border)] rounded-lg bg-[var(--card)] disabled:opacity-50"
                    >
                      {#if parts.data.length === 0}<option value="">Tidak ada part</option>{/if}
                      {#each parts.data as part (part.partCode)}
                        <option value={part.partCode}>{part.partName} ({part.partCode})</option>
                      {/each}
                    </select>
                    <select
                      disabled={!station.online || isBusy || !hasSideView}
                      value={view}
                      onchange={(event) => inspectionView = { ...inspectionView, [station.stationId]: (event.currentTarget as HTMLSelectElement).value as DimensionView }}
                      class="px-2.5 py-1.5 text-xs border border-[var(--border)] rounded-lg bg-[var(--card)] disabled:opacity-50"
                    >
                      <option value="top">Tampak Atas</option>
                      <option value="side">Tampak Samping</option>
                    </select>
                    <button
                      disabled={!station.online || isBusy || !partCode}
                      onclick={() => runCommand(station.stationId, 'Mulai', () => api.startAgent(station.stationId, partCode, view))}
                      class="flex items-center justify-center gap-1 px-3 py-1.5 bg-blue-600 text-white rounded-lg text-xs hover:bg-blue-700 disabled:opacity-50 shrink-0"
                    >
                      <Play class="w-3.5 h-3.5" /> Mulai
                    </button>
                  </div>
                {:else}
                  <div class="grid grid-cols-[1fr_1fr_1fr_1fr] gap-1.5">
                    <select
                      disabled={!station.online || isBusy || !hasSideView}
                      value={view}
                      onchange={(event) => inspectionView = { ...inspectionView, [station.stationId]: (event.currentTarget as HTMLSelectElement).value as DimensionView }}
                      class="px-2 py-1.5 text-xs border border-[var(--border)] rounded-lg bg-[var(--card)] disabled:opacity-50"
                    >
                      <option value="top">Atas</option>
                      <option value="side">Samping</option>
                    </select>
                    <button
                      disabled={!station.online || isBusy || phase === 'calibrating'}
                      onclick={() => runCommand(station.stationId, 'Capture', () => api.captureNow(station.stationId, view))}
                      title="Simpan inspeksi sekarang"
                      class="flex items-center justify-center gap-1 px-2 py-1.5 bg-blue-600 text-white rounded-lg text-xs hover:bg-blue-700 disabled:opacity-50"
                    >
                      <Camera class="w-3.5 h-3.5" /> Capture
                    </button>
                    <button
                      disabled={!station.online || isBusy}
                      onclick={() => runCommand(station.stationId, 'Kalibrasi', () => api.recalibrate(station.stationId))}
                      class="flex items-center justify-center gap-1 px-2 py-1.5 bg-amber-500 text-white rounded-lg text-xs hover:bg-amber-600 disabled:opacity-50"
                    >
                      <RefreshCcw class="w-3.5 h-3.5" /> Kalibrasi
                    </button>
                    <button
                      disabled={!station.online || isBusy}
                      onclick={() => runCommand(station.stationId, 'Berhenti', () => api.stopAgent(station.stationId))}
                      class="flex items-center justify-center gap-1 px-2 py-1.5 bg-red-600 text-white rounded-lg text-xs hover:bg-red-700 disabled:opacity-50"
                    >
                      <StopCircle class="w-3.5 h-3.5" /> Stop
                    </button>
                  </div>
                {/if}
              </div>
            </div>
          {/each}
        </div>
      {/if}
    </div>

    <div class="space-y-4">
      <div class="bg-[var(--card)] border border-[var(--border)] rounded-xl overflow-hidden">
        <div class="p-4 border-b border-[var(--border)] flex items-center justify-between gap-3">
          <div>
            <h3 class="text-sm">Stats Dimensi</h3>
            <p class="text-xs text-[var(--muted-foreground)] mt-0.5">
              {selectedDetection ? selectedDetection.label : 'Pilih bounding box untuk melihat detail'}
            </p>
          </div>
          <button
            type="button"
            onclick={() => { selectedDetectionKey = null; boxesHidden = true; }}
            class="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg border border-[var(--border)] text-xs hover:bg-[var(--accent)]"
          >
            <RotateCcw class="w-3.5 h-3.5" /> Reset
          </button>
        </div>

        <div class="p-4 space-y-3">
          <div class="grid grid-cols-3 gap-2 text-center">
            <div class="rounded-lg bg-[var(--accent)] p-3">
              <div class="text-[11px] text-[var(--muted-foreground)]">Status</div>
              <div class="text-lg font-medium {selectedDetection?.status === 'NG' ? 'text-red-600' : selectedDetection ? 'text-green-600' : 'text-[var(--muted-foreground)]'}">
                {selectedDetection?.status ?? '-'}
              </div>
            </div>
            <div class="rounded-lg bg-[var(--accent)] p-3">
              <div class="text-[11px] text-[var(--muted-foreground)]">Confidence</div>
              <div class="text-lg font-medium">{selectedDetection ? `${selectedDetection.confidenceScore}%` : '-'}</div>
            </div>
            <div class="rounded-lg bg-[var(--accent)] p-3">
              <div class="text-[11px] text-[var(--muted-foreground)]">OK / NG</div>
              <div class="text-lg font-medium"><span class="text-green-600">{okCount}</span> / <span class="text-red-600">{ngCount}</span></div>
            </div>
          </div>

          {#if measurements.length === 0}
            <div class="rounded-lg border border-dashed border-[var(--border)] p-6 text-center text-sm text-[var(--muted-foreground)]">
              Belum ada dimensi yang dipilih.
            </div>
          {:else}
            <div class="space-y-2">
              {#each measurements as measurement (measurement.dimensionName)}
                {@const delta = measurement.measured - measurement.nominal}
                {@const statusLabel = measurement.status === 'UNREADABLE' ? 'Tidak terbaca' : measurement.status}
                <div class="rounded-lg border border-[var(--border)] p-3">
                  <div class="flex items-start justify-between gap-3">
                    <div>
                      <div class="text-sm font-medium">{measurement.dimensionName}</div>
                      <div class="text-[11px] text-[var(--muted-foreground)]">
                        Toleransi {measurement.lowerLimit} - {measurement.upperLimit} {measurement.unit}
                      </div>
                    </div>
                    <span class="text-[11px] px-2 py-0.5 rounded-full {measurement.status === 'OK' ? 'bg-green-100 text-green-700' : 'bg-red-100 text-red-700'}">
                      {statusLabel}
                    </span>
                  </div>
                  <div class="grid grid-cols-3 gap-2 mt-3 text-xs">
                    <div><div class="text-[var(--muted-foreground)]">Measured</div><div class="font-medium">{measurement.measured} {measurement.unit}</div></div>
                    <div><div class="text-[var(--muted-foreground)]">Nominal</div><div class="font-medium">{measurement.nominal} {measurement.unit}</div></div>
                    <div><div class="text-[var(--muted-foreground)]">Delta</div><div class="font-medium {Math.abs(delta) > 0 ? 'text-amber-700' : ''}">{delta.toFixed(3)} {measurement.unit}</div></div>
                  </div>
                </div>
              {/each}
            </div>
          {/if}
        </div>
      </div>

      <div class="bg-[var(--card)] border border-[var(--border)] rounded-xl overflow-hidden">
        <div class="p-4 border-b border-[var(--border)] flex items-center justify-between">
          <h3 class="text-sm">Sesi ini</h3>
          <span class="text-xs text-[var(--muted-foreground)]">{latestInspections.length} data</span>
        </div>
        <div class="grid grid-cols-3 gap-2 p-4 border-b border-[var(--border)] text-center text-sm">
          <div><div class="text-xl font-medium">{sessionStats.total}</div><div class="text-xs text-[var(--muted-foreground)]">Total</div></div>
          <div><div class="text-xl font-medium text-green-600">{sessionStats.ok}</div><div class="text-xs text-[var(--muted-foreground)]">OK</div></div>
          <div><div class="text-xl font-medium text-red-600">{sessionStats.ngRate}%</div><div class="text-xs text-[var(--muted-foreground)]">NG</div></div>
        </div>
        <div class="p-4 space-y-3 max-h-[420px] overflow-y-auto">
          {#if latestInspections.length === 0}
            <div class="text-center py-8 text-[var(--muted-foreground)] text-sm">Belum ada event inspeksi.</div>
          {:else}
            {#each latestInspections as inspection (inspection.id)}
              <div class="p-3 rounded-lg border {inspection.status === 'OK' ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}">
                <div class="flex items-center justify-between mb-1">
                  <div class="flex items-center gap-2">
                    {#if inspection.status === 'OK'}
                      <CheckCircle class="w-4 h-4 text-green-600" />
                    {:else}
                      <XCircle class="w-4 h-4 text-red-600" />
                    {/if}
                    <span class="text-sm" style="font-weight: 500">{inspection.partName} ({inspection.partCode})</span>
                  </div>
                  <span class="text-xs text-[var(--muted-foreground)]">{new Date(inspection.timestamp).toLocaleTimeString('id-ID')}</span>
                </div>
                <div class="text-xs text-[var(--muted-foreground)]">
                  {inspection.stationId} - {inspection.detections[0]?.label ?? 'Objek'} - {inspection.confidenceScore}%
                </div>
              </div>
            {/each}
          {/if}
        </div>
      </div>
    </div>
  </div>
</div>

// Frontend/src/app/pages/LiveTrackingPage.tsx
import { useEffect, useMemo, useState } from 'react';
import {
  Video, CheckCircle, XCircle, Play, StopCircle, Camera, RefreshCcw, Hand, Zap,
} from 'lucide-react';
import { useInspections } from '../hooks/useInspections';
import { useStations } from '../hooks/useStations';
import { useAgents } from '../hooks/useAgents';
import { useFrameStream } from '../hooks/useFrameStream';
import { useParts } from '../hooks/useParts';
import { useShiftSchedules } from '../hooks/useShiftSchedules';
import { useBatches } from '../hooks/useBatches';
import { api, getErrorMessage } from '../services/api';
import type {
  AgentInfo, InspectionResult, ObjectDetection, StationPhase, StationStatusEvent,
} from '../types/api';

interface MergedStation {
  stationId: string;
  online: boolean;
  running: boolean;
  fps?: number;
  phase?: StationPhase;
  activePartCode?: string;
}

type ViewMode = 'multi' | 'focus' | 'wall';

function mergeStations(agents: AgentInfo[], stations: StationStatusEvent[]): MergedStation[] {
  const map = new Map<string, MergedStation>();
  for (const station of stations) {
    map.set(station.stationId, {
      stationId: station.stationId,
      online: station.state === 'online',
      running: Boolean(station.running),
      fps: station.fps,
      phase: station.phase,
      activePartCode: station.activePartCode,
    });
  }
  for (const agent of agents) {
    const existing = map.get(agent.stationId);
    map.set(agent.stationId, {
      stationId: agent.stationId,
      online: agent.online,
      running: agent.running,
      fps: existing?.fps,
      phase: agent.online ? existing?.phase : 'idle',
      activePartCode: existing?.activePartCode,
    });
  }
  return [...map.values()].sort((a, b) => a.stationId.localeCompare(b.stationId));
}

const PHASE_LABELS: Record<StationPhase, { text: string; tone: string; icon: typeof Camera }> = {
  idle: { text: 'Idle', tone: 'bg-gray-100 text-gray-700', icon: StopCircle },
  calibrating: { text: 'Kalibrasi', tone: 'bg-amber-100 text-amber-700', icon: RefreshCcw },
  ready: { text: 'Siap', tone: 'bg-blue-100 text-blue-700', icon: Hand },
  stabilizing: { text: 'Deteksi', tone: 'bg-purple-100 text-purple-700', icon: Zap },
  locked: { text: 'Terkunci', tone: 'bg-green-100 text-green-700', icon: CheckCircle },
};

export function LiveTrackingPage() {
  const inspections = useInspections(20);
  const stations = useStations();
  const agents = useAgents();
  const parts = useParts();
  const shifts = useShiftSchedules();
  const batches = useBatches();
  const [busy, setBusy] = useState<Record<string, boolean>>({});
  const [toast, setToast] = useState<{ text: string; tone: 'info' | 'error' } | null>(null);
  const [selectedPart, setSelectedPart] = useState<Record<string, string>>({});
  const [selectedShift, setSelectedShift] = useState<Record<string, 'A' | 'B' | 'C'>>({});
  const [viewMode, setViewMode] = useState<ViewMode>('multi');
  const [focusStation, setFocusStation] = useState<string | null>(null);
  const [selectedDetection, setSelectedDetection] = useState<ObjectDetection | null>(null);

  const latestInspections = inspections.data.slice(0, 10);
  const loading = inspections.loading || stations.loading || agents.loading || parts.loading || shifts.loading || batches.loading;
  const error = inspections.error || stations.error || agents.error || parts.error || shifts.error || batches.error;

  const merged = useMemo(() => mergeStations(agents.data, stations.data), [agents.data, stations.data]);
  const visibleStations = useMemo(() => {
    if (viewMode === 'focus' && focusStation) return merged.filter((station) => station.stationId === focusStation);
    return merged;
  }, [focusStation, merged, viewMode]);
  const frames = useFrameStream(visibleStations.map((station) => station.stationId));
  const latestByStation = useMemo(() => {
    const map = new Map<string, InspectionResult>();
    for (const inspection of inspections.data) {
      if (!map.has(inspection.stationId)) map.set(inspection.stationId, inspection);
    }
    return map;
  }, [inspections.data]);

  useEffect(() => {
    if (parts.data.length === 0) return;
    setSelectedPart((current) => {
      const next = { ...current };
      let changed = false;
      for (const s of merged) {
        if (!next[s.stationId]) {
          next[s.stationId] = s.activePartCode ?? parts.data[0].partCode;
          changed = true;
        }
      }
      return changed ? next : current;
    });
  }, [merged, parts.data]);

  useEffect(() => {
    const activeShift = shifts.data.find((shift) => shift.active)?.shift ?? 'A';
    setSelectedShift((current) => {
      const next = { ...current };
      let changed = false;
      for (const s of merged) {
        if (!next[s.stationId]) {
          next[s.stationId] = activeShift;
          changed = true;
        }
      }
      return changed ? next : current;
    });
  }, [merged, shifts.data]);

  const showToast = (text: string, tone: 'info' | 'error' = 'info') => {
    setToast({ text, tone });
    window.setTimeout(() => setToast(null), 2800);
  };

  const runCommand = async (stationId: string, label: string, fn: () => Promise<unknown>) => {
    setBusy((current) => ({ ...current, [stationId]: true }));
    try {
      await fn();
      showToast(`${label}: ${stationId}`);
      await agents.refresh();
    } catch (err) {
      showToast(getErrorMessage(err), 'error');
    } finally {
      setBusy((current) => ({ ...current, [stationId]: false }));
    }
  };

  const onlineCount = merged.filter((s) => s.online).length;
  const runningCount = merged.filter((s) => s.running).length;
  const shiftStats = latestInspections.reduce((acc, item) => {
    acc.total += 1;
    if (item.status === 'OK') acc.ok += 1;
    if (item.status === 'NG') acc.ng += 1;
    return acc;
  }, { total: 0, ok: 0, ng: 0 });
  const shiftNgRate = shiftStats.total > 0 ? ((shiftStats.ng / shiftStats.total) * 100).toFixed(1) : '0.0';

  return (
    <div className="space-y-4">
      {toast && (
        <div className={`fixed top-4 right-4 z-50 px-4 py-2.5 rounded-lg shadow-lg text-sm text-white ${toast.tone === 'error' ? 'bg-red-600' : 'bg-blue-600'}`}>
          {toast.text}
        </div>
      )}

      <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
        <div>
          <h1>Live Tracking</h1>
          <p className="text-[var(--muted-foreground)] text-sm mt-1">
            Streaming berjalan terus. Data masuk saat operator menekan Capture.
          </p>
        </div>
        <div className="flex flex-wrap items-center gap-2 text-xs">
          {(['multi', 'focus', 'wall'] as ViewMode[]).map((mode) => (
            <button
              key={mode}
              onClick={() => setViewMode(mode)}
              className={`px-3 py-1 rounded-full ${viewMode === mode ? 'bg-blue-600 text-white' : 'bg-[var(--accent)] text-[var(--foreground)]'}`}
            >
              {mode === 'multi' ? 'Multi' : mode === 'focus' ? 'Focus' : 'Wall'}
            </button>
          ))}
          <span className="px-2 py-1 rounded-full bg-green-100 text-green-700">
            {onlineCount} Online
          </span>
          <span className="px-2 py-1 rounded-full bg-blue-100 text-blue-700">
            {runningCount} Running
          </span>
        </div>
      </div>

      {error && (
        <div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-4 text-sm flex items-center justify-between gap-3">
          <span>{error}</span>
          <button
            onClick={() => { inspections.reload(); stations.reload(); agents.reload(); parts.reload(); }}
            className="px-3 py-1.5 bg-red-600 text-white rounded-lg text-xs"
          >
            Coba lagi
          </button>
        </div>
      )}

      <div className="grid lg:grid-cols-[1fr_320px] gap-4">
        <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-sm">Kamera</h3>
            <span className="text-xs text-[var(--muted-foreground)]">{merged.length} station</span>
          </div>

          {loading && merged.length === 0 ? (
            <div className="grid sm:grid-cols-2 gap-3">
              {[0, 1].map((i) => (
                <div key={i} className="h-72 bg-[var(--accent)] rounded animate-pulse" />
              ))}
            </div>
          ) : merged.length === 0 ? (
            <div className="text-center py-12 text-[var(--muted-foreground)]">
              <Video className="w-12 h-12 mx-auto mb-3 opacity-30" />
              <p className="text-sm">Belum ada agent yang terhubung.</p>
              <p className="text-xs mt-1">Jalankan agent di mesin local untuk mulai streaming.</p>
            </div>
          ) : (
            <div className={viewMode === 'wall' ? 'grid md:grid-cols-3 gap-3' : viewMode === 'focus' ? 'grid gap-4' : 'grid xl:grid-cols-2 gap-4'}>
              {visibleStations.map((s) => {
                const frameUrl = frames[s.stationId];
                const isBusy = busy[s.stationId];
                const phase = s.phase ?? (s.running ? 'ready' : 'idle');
                const PhaseMeta = PHASE_LABELS[phase];
                const PhaseIcon = PhaseMeta.icon;
                const partCode = selectedPart[s.stationId] ?? '';
                const activePart = parts.data.find((p) => p.partCode === s.activePartCode);
                const shift = selectedShift[s.stationId] ?? 'A';
                const latest = latestByStation.get(s.stationId);
                const detections = latest?.detections ?? [];
                const openBatch = batches.data.find((batch) => batch.status === 'open' && batch.partCode === partCode && batch.shift === shift);

                return (
                  <div key={s.stationId} className="border border-[var(--border)] rounded-lg overflow-hidden flex flex-col">
                    <button onClick={() => { setFocusStation(s.stationId); setViewMode('focus'); }} className={`aspect-video bg-black flex items-center justify-center relative ${viewMode === 'focus' ? 'min-h-[480px]' : ''}`}>
                      {s.running && frameUrl ? (
                        <img src={frameUrl} alt={s.stationId} className="w-full h-full object-contain" />
                      ) : (
                        <div className="text-gray-500 text-xs flex flex-col items-center">
                          <Video className="w-8 h-8 mb-2 opacity-50" />
                          {s.online ? (s.running ? 'Menunggu frame...' : 'Idle — pilih part lalu klik Mulai') : 'Agent offline'}
                        </div>
                      )}
                      {detections.map((detection) => (
                        <button
                          key={detection.id}
                          onClick={(event) => { event.stopPropagation(); setSelectedDetection(detection); }}
                          className={`absolute border-2 ${detection.status === 'OK' ? 'border-green-400' : 'border-red-400'} bg-transparent`}
                          style={{
                            left: `${detection.bbox.x}%`,
                            top: `${detection.bbox.y}%`,
                            width: `${detection.bbox.width}%`,
                            height: `${detection.bbox.height}%`,
                          }}
                          title={detection.label}
                        />
                      ))}
                      <div className="absolute top-2 left-2 flex flex-col gap-1">
                        <span className={`text-[10px] px-2 py-0.5 rounded-full ${s.online ? 'bg-green-500 text-white' : 'bg-red-500 text-white'}`}>
                          {s.online ? 'ONLINE' : 'OFFLINE'}
                        </span>
                        {s.running && (
                          <span className={`text-[10px] px-2 py-0.5 rounded-full inline-flex items-center gap-1 ${PhaseMeta.tone}`}>
                            <PhaseIcon className="w-3 h-3" />
                            {PhaseMeta.text}
                          </span>
                        )}
                      </div>
                      {s.fps && s.running ? (
                        <div className="absolute top-2 right-2 text-[10px] bg-black/60 text-white px-2 py-0.5 rounded-full">
                          {s.fps.toFixed(1)} FPS
                        </div>
                      ) : null}
                    </button>

                    <div className="p-3 space-y-2.5">
                      <div className="flex items-center justify-between gap-2">
                        <div className="min-w-0">
                          <div className="text-sm truncate" style={{ fontWeight: 500 }}>{s.stationId}</div>
                          <div className="text-[11px] text-[var(--muted-foreground)] truncate">
                            {activePart ? `${activePart.partName} • ${activePart.partCode}` : 'Belum ada part'}
                          </div>
                        </div>
                      </div>

                      {!s.running ? (
                        <div className="grid md:grid-cols-[1fr_90px_120px] gap-2">
                          <select
                            disabled={!s.online || isBusy || parts.data.length === 0}
                            value={partCode}
                            onChange={(e) => setSelectedPart((c) => ({ ...c, [s.stationId]: e.target.value }))}
                            className="flex-1 min-w-0 px-2.5 py-1.5 text-xs border border-[var(--border)] rounded-lg bg-[var(--card)] disabled:opacity-50"
                          >
                            {parts.data.length === 0 && <option value="">Tidak ada part</option>}
                            {parts.data.map((p) => (
                              <option key={p.partCode} value={p.partCode}>{p.partName} ({p.partCode})</option>
                            ))}
                          </select>
                          <select
                            disabled={!s.online || isBusy}
                            value={shift}
                            onChange={(e) => setSelectedShift((c) => ({ ...c, [s.stationId]: e.target.value as 'A' | 'B' | 'C' }))}
                            className="px-2.5 py-1.5 text-xs border border-[var(--border)] rounded-lg bg-[var(--card)] disabled:opacity-50"
                          >
                            {shifts.data.filter((item) => item.active).map((item) => (
                              <option key={item.id} value={item.shift}>{item.shift}</option>
                            ))}
                          </select>
                          <button
                            disabled={!s.online || isBusy || !partCode}
                            onClick={() => runCommand(s.stationId, 'Mulai', () => api.startAgent(s.stationId, partCode, shift, openBatch?.batchNo))}
                            className="flex items-center gap-1 px-3 py-1.5 bg-blue-600 text-white rounded-lg text-xs hover:bg-blue-700 disabled:opacity-50 shrink-0"
                          >
                            <Play className="w-3.5 h-3.5" /> Mulai
                          </button>
                        </div>
                      ) : (
                        <div className="grid grid-cols-3 gap-1.5">
                          <button
                            disabled={!s.online || isBusy || phase === 'calibrating'}
                            onClick={() => runCommand(s.stationId, 'Capture', () => api.captureNow(s.stationId))}
                            title="Simpan inspeksi sekarang"
                            className="flex items-center justify-center gap-1 px-2 py-1.5 bg-blue-600 text-white rounded-lg text-xs hover:bg-blue-700 disabled:opacity-50"
                          >
                            <Camera className="w-3.5 h-3.5" /> Capture
                          </button>
                          <button
                            disabled={!s.online || isBusy}
                            onClick={() => runCommand(s.stationId, 'Recalibrate', () => api.recalibrate(s.stationId))}
                            title="Ulangi kalibrasi background (kamera harus kosong)"
                            className="flex items-center justify-center gap-1 px-2 py-1.5 bg-amber-500 text-white rounded-lg text-xs hover:bg-amber-600 disabled:opacity-50"
                          >
                            <RefreshCcw className="w-3.5 h-3.5" /> Kalibrasi
                          </button>
                          <button
                            disabled={!s.online || isBusy}
                            onClick={() => runCommand(s.stationId, 'Berhenti', () => api.stopAgent(s.stationId))}
                            className="flex items-center justify-center gap-1 px-2 py-1.5 bg-red-600 text-white rounded-lg text-xs hover:bg-red-700 disabled:opacity-50"
                          >
                            <StopCircle className="w-3.5 h-3.5" /> Stop
                          </button>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        <div className="bg-[var(--card)] border border-[var(--border)] rounded-xl overflow-hidden">
          <div className="p-4 border-b border-[var(--border)] flex items-center justify-between">
            <h3 className="text-sm">Shift ini</h3>
            <span className="text-xs text-[var(--muted-foreground)]">{latestInspections.length} data</span>
          </div>
          <div className="grid grid-cols-3 gap-2 p-4 border-b border-[var(--border)] text-center text-sm">
            <div><div className="text-xl font-medium">{shiftStats.total}</div><div className="text-xs text-[var(--muted-foreground)]">Total</div></div>
            <div><div className="text-xl font-medium text-green-600">{shiftStats.ok}</div><div className="text-xs text-[var(--muted-foreground)]">OK</div></div>
            <div><div className="text-xl font-medium text-red-600">{shiftNgRate}%</div><div className="text-xs text-[var(--muted-foreground)]">NG</div></div>
          </div>
          {selectedDetection && (
            <div className="p-4 border-b border-[var(--border)]">
              <div className="flex items-center justify-between mb-2">
                <h4 className="text-sm">{selectedDetection.label}</h4>
                <span className={`text-xs ${selectedDetection.status === 'OK' ? 'text-green-600' : 'text-red-600'}`}>{selectedDetection.status}</span>
              </div>
              <div className="space-y-1">
                {selectedDetection.measurements.map((measurement) => (
                  <div key={measurement.dimensionName} className="flex justify-between text-xs">
                    <span>{measurement.dimensionName}</span>
                    <span>{measurement.measured} {measurement.unit}</span>
                  </div>
                ))}
              </div>
            </div>
          )}
          <div className="p-4 space-y-3 max-h-[420px] overflow-y-auto">
            {latestInspections.length === 0 ? (
              <div className="text-center py-8 text-[var(--muted-foreground)] text-sm">
                Belum ada event inspeksi.
              </div>
            ) : (
              latestInspections.map((r: InspectionResult) => (
                <div key={r.id} className={`p-3 rounded-lg border ${r.status === 'OK' ? 'bg-green-50 border-green-200' : 'bg-red-50 border-red-200'}`}>
                  <div className="flex items-center justify-between mb-1">
                    <div className="flex items-center gap-2">
                      {r.status === 'OK' ? <CheckCircle className="w-4 h-4 text-green-600" /> : <XCircle className="w-4 h-4 text-red-600" />}
                      <span className="text-sm" style={{ fontWeight: 500 }}>{r.partName} ({r.partCode})</span>
                    </div>
                    <span className="text-xs text-[var(--muted-foreground)]">{new Date(r.timestamp).toLocaleTimeString('id-ID')}</span>
                  </div>
                  <div className="text-xs text-[var(--muted-foreground)]">
                    {r.stationId} • {r.detections.length || 1} objek • {r.confidenceScore}%
                  </div>
                </div>
              ))
            )}
          </div>
        </div>
      </div>
    </div>
  );
}
