// frontend/src/routes/PartConfigurationPage.svelte
<script lang="ts">
  import { ChevronDown, Edit3, Plus, Search, Trash2 } from 'lucide-svelte';
  import { navigate } from 'svelte-routing';
  import { useParts } from '$lib/hooks/useParts.svelte';
  import { api, getErrorMessage } from '$lib/services/api';
  import type { DimensionKind, DimensionView, PartType } from '$lib/types/api';
  import Notice from '$lib/components/Notice.svelte';

  const KIND_LABELS: Record<DimensionKind, string> = {
    width: 'Lebar',
    length: 'Panjang',
    diameter: 'Diameter',
    outer_diameter: 'Diameter luar',
    inner_diameter: 'Diameter dalam',
    hole_diameter: 'Diameter lubang',
  };

  const VIEW_LABELS: Record<DimensionView, string> = {
    top: 'Menghadap Kamera',
    side: 'Menyamping dari Kamera',
  };

  const parts = useParts();

  let search = $state('');
  let vendorFilter = $state('');
  let expandedId = $state<string | null>(null);
  let error = $state<string | null>(null);

  const vendors = $derived([...new Set(parts.data.map((part) => part.vendor))].sort());

  const filtered = $derived.by(() => {
    const q = search.trim().toLowerCase();
    return parts.data.filter((part) => {
      if (vendorFilter && part.vendor !== vendorFilter) return false;
      if (!q) return true;
      return part.partName.toLowerCase().includes(q)
        || part.partCode.toLowerCase().includes(q)
        || part.vendor.toLowerCase().includes(q);
    });
  });

  const viewSummary = (part: PartType) => {
    const top = part.dimensions.filter((dimension) => dimension.view === 'top').length;
    const side = part.dimensions.filter((dimension) => dimension.view === 'side').length;
    if (top > 0 && side > 0) return `Menghadap Kamera ${top} / Menyamping dari Kamera ${side}`;
    if (side > 0) return `Menyamping dari Kamera ${side}`;
    return `Menghadap Kamera ${top}`;
  };

  const remove = async (part: PartType) => {
    if (!window.confirm(`Hapus part ${part.partCode}?`)) return;
    error = null;
    try {
      await api.deletePart(part.id);
      parts.reload();
      if (expandedId === part.id) expandedId = null;
    } catch (err) {
      error = getErrorMessage(err);
    }
  };
</script>

<div class="space-y-6 select-none font-sans">
  <div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4">
    <div>
      <h1 class="text-slate-900 dark:text-white tracking-tight">Konfigurasi Part</h1>
    </div>
    <button
      onclick={() => navigate('/part-configuration/new')}
      class="inline-flex items-center justify-center gap-2 px-4.5 py-2.5 bg-gradient-to-r from-indigo-500 to-violet-600 hover:from-indigo-600 hover:to-violet-700 text-white rounded-xl text-xs font-bold shadow-md shadow-indigo-500/10 active:scale-[0.98] transition-premium self-start sm:self-auto shrink-0"
    >
      <Plus class="w-4 h-4" /> Part Baru
    </button>
  </div>

  {#if error}<Notice text={error} />{/if}
  {#if parts.error}<Notice text={parts.error} />{/if}

  <div class="flex flex-col sm:flex-row gap-3">
    <div class="relative flex-1 min-w-[240px]">
      <Search class="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400" />
      <input
        bind:value={search}
        class="input pl-10 pr-4 py-2.5"
        placeholder="Cari part, kode, atau vendor..."
      />
    </div>
    <select bind:value={vendorFilter} class="input min-w-[160px] w-auto py-2.5 px-3">
      <option value="">Semua Vendor</option>
      {#each vendors as vendor (vendor)}
        <option value={vendor}>{vendor}</option>
      {/each}
    </select>
  </div>

  <div class="text-xs text-[var(--muted-foreground)] font-bold tracking-wide bg-slate-100/50 dark:bg-slate-900/30 border border-[var(--border)] w-fit px-3 py-1.5 rounded-lg shadow-sm">
    Ditemukan <span class="text-indigo-500 font-mono-data">{filtered.length}</span> Part
  </div>

  <div class="bg-[var(--card)] border border-[var(--border)] rounded-2xl shadow-sm overflow-hidden">
    <div class="overflow-x-auto">
      <table class="w-full text-sm">
        <thead>
          <tr class="bg-slate-50 dark:bg-slate-900/40 text-slate-700 dark:text-slate-200 border-b border-[var(--border)] text-left font-bold text-xs uppercase tracking-wider">
            <th class="px-5 py-4">Kode Part</th>
            <th class="px-5 py-4">Nama Produk</th>
            <th class="px-5 py-4">Vendor Partner</th>
            <th class="px-5 py-4 text-center">Jumlah Dimensi</th>
            <th class="px-5 py-4">Orientasi Barang</th>
            <th class="px-5 py-4 text-right">Aksi</th>
          </tr>
        </thead>
        <tbody class="divide-y divide-[var(--border)] text-slate-800 dark:text-slate-200">
          {#if parts.loading && parts.data.length === 0}
            {#each Array(6) as _row, i (i)}
              <tr class="animate-pulse" aria-hidden="true">
                <td class="px-5 py-3.5"><div class="h-4 w-20 rounded bg-slate-200 dark:bg-slate-700/50"></div></td>
                <td class="px-5 py-3.5"><div class="h-4 w-36 rounded bg-slate-200 dark:bg-slate-700/50"></div></td>
                <td class="px-5 py-3.5"><div class="h-4 w-24 rounded bg-slate-200 dark:bg-slate-700/50"></div></td>
                <td class="px-5 py-3.5"><div class="h-4 w-6 rounded bg-slate-200 dark:bg-slate-700/50 mx-auto"></div></td>
                <td class="px-5 py-3.5"><div class="h-4 w-40 rounded bg-slate-200 dark:bg-slate-700/50"></div></td>
                <td class="px-5 py-3.5">
                  <div class="flex items-center justify-end gap-1.5">
                    <div class="h-8 w-8 rounded-xl bg-slate-200 dark:bg-slate-700/50"></div>
                    <div class="h-8 w-8 rounded-xl bg-slate-200 dark:bg-slate-700/50"></div>
                    <div class="h-8 w-8 rounded-xl bg-slate-200 dark:bg-slate-700/50"></div>
                  </div>
                </td>
              </tr>
            {/each}
          {:else}
          {#each filtered as part (part.id)}
            {@const isExpanded = expandedId === part.id}
            <tr
              class="cursor-pointer transition-premium duration-150 {isExpanded ? 'bg-indigo-500/5 dark:bg-indigo-950/20' : 'hover:bg-slate-50/50 dark:hover:bg-slate-900/10'}"
              onclick={() => expandedId = isExpanded ? null : part.id}
            >
              <td class="px-5 py-3.5 font-bold font-mono-data text-xs text-indigo-600 dark:text-indigo-400 whitespace-nowrap">{part.partCode}</td>
              <td class="px-5 py-3.5 font-bold text-slate-900 dark:text-white">{part.partName}</td>
              <td class="px-5 py-3.5 font-semibold text-slate-600 dark:text-slate-300">{part.vendor}</td>
              <td class="px-5 py-3.5 text-center font-bold font-mono-data text-xs">{part.dimensions.length}</td>
              <td class="px-5 py-3.5 text-xs text-slate-500 dark:text-slate-400 font-semibold">{viewSummary(part)}</td>
              <td class="px-5 py-3.5" onclick={(event) => event.stopPropagation()}>
                <div class="flex items-center justify-end gap-1.5">
                  <button
                    type="button"
                    onclick={() => navigate(`/part-configuration/${part.id}/edit`)}
                    class="p-2 border border-[var(--border)] hover:bg-[var(--accent)] hover:text-[var(--accent-foreground)] rounded-xl transition-premium shadow-sm text-slate-500 dark:text-slate-400"
                    title="Edit spesifikasi part"
                  >
                    <Edit3 class="w-4 h-4" />
                  </button>
                  <button
                    type="button"
                    onclick={() => void remove(part)}
                    class="p-2 border border-rose-500/10 hover:bg-rose-500/10 rounded-xl transition-premium shadow-sm text-rose-500"
                    title="Hapus part"
                  >
                    <Trash2 class="w-4 h-4" />
                  </button>
                  <button
                    type="button"
                    onclick={() => expandedId = isExpanded ? null : part.id}
                    class="p-2 border border-[var(--border)] hover:bg-slate-100 dark:hover:bg-slate-800 rounded-xl transition-premium text-slate-500 dark:text-slate-400"
                  >
                    <ChevronDown class="w-4 h-4 transition-transform duration-300 {isExpanded ? 'rotate-180' : ''}" />
                  </button>
                </div>
              </td>
            </tr>
            {#if isExpanded}
              <tr>
                <td colspan="6" class="px-5 py-5 bg-slate-50/50 dark:bg-slate-900/20 border-t border-b border-[var(--border)]">
                  <div class="overflow-hidden rounded-2xl border border-[var(--border)] bg-[var(--card)] shadow-inner">
                    <table class="w-full text-xs">
                      <thead>
                        <tr class="bg-slate-50 dark:bg-slate-900/40 text-slate-600 dark:text-slate-400 border-b border-[var(--border)] text-left font-bold text-[10px] uppercase tracking-wider">
                          <th class="px-4 py-3">Nama Dimensi</th>
                          <th class="px-4 py-3">Orientasi Barang</th>
                          <th class="px-4 py-3">Kategori</th>
                          <th class="px-4 py-3 text-right">Nilai Nominal</th>
                          <th class="px-4 py-3 text-right">Batas Bawah (Min)</th>
                          <th class="px-4 py-3 text-right">Batas Atas (Max)</th>
                        </tr>
                      </thead>
                      <tbody class="divide-y divide-[var(--border)] text-slate-800 dark:text-slate-300 font-semibold font-mono-data">
                        {#each part.dimensions as dimension (dimension.id)}
                          <tr class="hover:bg-slate-50/30 dark:hover:bg-slate-900/10">
                            <td class="px-4 py-2.5 font-bold font-sans text-slate-900 dark:text-white">{dimension.name}</td>
                            <td class="px-4 py-2.5 font-sans">{VIEW_LABELS[dimension.view]}</td>
                            <td class="px-4 py-2.5 font-sans">{KIND_LABELS[dimension.kind]}</td>
                            <td class="px-4 py-2.5 text-right text-slate-900 dark:text-white font-bold">{dimension.nominal} {dimension.unit}</td>
                            <td class="px-4 py-2.5 text-right text-rose-500">{dimension.lowerLimit} {dimension.unit}</td>
                            <td class="px-4 py-2.5 text-right text-emerald-500">{dimension.upperLimit} {dimension.unit}</td>
                          </tr>
                        {/each}
                      </tbody>
                    </table>
                  </div>
                </td>
              </tr>
            {/if}
          {/each}

          {#if !parts.loading && filtered.length === 0}
            <tr>
              <td colspan="6" class="px-5 py-16 text-center text-[var(--muted-foreground)] font-medium">
                Tidak ditemukan part terdaftar yang cocok dengan filter pencarian.
              </td>
            </tr>
          {/if}
          {/if}
        </tbody>
      </table>
    </div>
  </div>
</div>

// Frontend/src/app/pages/PartConfigurationPage.tsx
import { useEffect, useState, type ReactNode } from 'react';
import { Plus, Save, Trash2, XCircle } from 'lucide-react';
import { useParts } from '../hooks/useParts';
import { api, getErrorMessage } from '../services/api';
import type { DimensionKind, DimensionSpec, DimensionView, PartType } from '../types/api';

const KIND_OPTIONS: { value: DimensionKind; label: string; note: string }[] = [
  { value: 'width', label: 'Width', note: 'Lebar horizontal pada view aktif' },
  { value: 'length', label: 'Length', note: 'Panjang vertikal pada view aktif' },
  { value: 'diameter', label: 'Diameter', note: 'Diameter umum dari lingkar luar' },
  { value: 'outer_diameter', label: 'Outer diameter', note: 'Diameter luar' },
  { value: 'inner_diameter', label: 'Inner diameter', note: 'Diameter lubang/area dalam' },
  { value: 'hole_diameter', label: 'Hole diameter', note: 'Alias untuk diameter lubang' },
];

const VIEW_OPTIONS: { value: DimensionView; label: string }[] = [
  { value: 'top', label: 'Tampak Atas' },
  { value: 'side', label: 'Tampak Samping' },
];

const emptyDimension = (): DimensionSpec => ({
  id: `dim-${Date.now()}-${Math.round(Math.random() * 1000)}`,
  name: 'Width',
  kind: 'width',
  view: 'top',
  nominal: 0,
  lowerLimit: 0,
  upperLimit: 0,
  unit: 'mm',
});

const emptyForm = (): Omit<PartType, 'id'> => ({
  partName: '',
  partCode: '',
  vendor: '',
  dimensions: [emptyDimension()],
});

export function PartConfigurationPage() {
  const parts = useParts();
  const [editingId, setEditingId] = useState<string | null>(null);
  const [form, setForm] = useState<Omit<PartType, 'id'>>(emptyForm);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (editingId && !parts.data.some((part) => part.id === editingId)) {
      setEditingId(null);
      setForm(emptyForm());
    }
  }, [editingId, parts.data]);

  const editPart = (part: PartType) => {
    setEditingId(part.id);
    setForm({
      partName: part.partName,
      partCode: part.partCode,
      vendor: part.vendor,
      dimensions: part.dimensions.length ? part.dimensions : [emptyDimension()],
    });
    setError(null);
  };

  const save = async () => {
    setSaving(true);
    setError(null);
    try {
      const payload = {
        ...form,
        dimensions: form.dimensions.map((dimension) => ({
          ...dimension,
          nominal: Number(dimension.nominal),
          lowerLimit: Number(dimension.lowerLimit),
          upperLimit: Number(dimension.upperLimit),
        })),
      };
      if (editingId) await api.updatePart(editingId, payload);
      else await api.createPart(payload);
      parts.reload();
      setEditingId(null);
      setForm(emptyForm());
    } catch (err) {
      setError(getErrorMessage(err));
    } finally {
      setSaving(false);
    }
  };

  const remove = async (part: PartType) => {
    if (!window.confirm(`Hapus part ${part.partCode}?`)) return;
    setError(null);
    try {
      await api.deletePart(part.id);
      parts.reload();
      if (editingId === part.id) {
        setEditingId(null);
        setForm(emptyForm());
      }
    } catch (err) {
      setError(getErrorMessage(err));
    }
  };

  const updateDimension = (index: number, patch: Partial<DimensionSpec>) => {
    setForm((current) => ({
      ...current,
      dimensions: current.dimensions.map((dimension, itemIndex) => itemIndex === index ? { ...dimension, ...patch } : dimension),
    }));
  };

  const removeDimension = (index: number) => {
    setForm((current) => ({
      ...current,
      dimensions: current.dimensions.length === 1
        ? current.dimensions
        : current.dimensions.filter((_, itemIndex) => itemIndex !== index),
    }));
  };

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between gap-3">
        <div>
          <h1>Konfigurasi Part</h1>
          <p className="text-sm text-[var(--muted-foreground)] mt-1">
            Atur spesifikasi dimensi 2D untuk tampak atas dan tampak samping.
          </p>
        </div>
        <button
          onClick={() => { setEditingId(null); setForm(emptyForm()); setError(null); }}
          className="inline-flex items-center gap-2 px-3 py-2 rounded-lg border border-[var(--border)] text-sm hover:bg-[var(--accent)]"
        >
          <Plus className="w-4 h-4" /> Part baru
        </button>
      </div>

      {error && <Notice text={error} />}
      {parts.error && <Notice text={parts.error} />}

      <div className="grid xl:grid-cols-[380px_1fr] gap-4">
        <section className="bg-[var(--card)] border border-[var(--border)] rounded-xl overflow-hidden">
          <div className="p-4 border-b border-[var(--border)]">
            <h3 className="text-sm">Daftar Part</h3>
          </div>
          <div className="divide-y divide-[var(--border)]">
            {parts.data.map((part) => (
              <div key={part.id} className={`p-4 ${editingId === part.id ? 'bg-blue-50/60' : ''}`}>
                <div className="flex items-start justify-between gap-3">
                  <button onClick={() => editPart(part)} className="text-left min-w-0">
                    <div className="font-medium truncate">{part.partName}</div>
                    <div className="text-xs text-[var(--muted-foreground)] truncate">{part.partCode} - {part.vendor}</div>
                    <div className="text-[11px] text-[var(--muted-foreground)] mt-1">
                      {part.dimensions.length} dimensi
                    </div>
                  </button>
                  <button onClick={() => void remove(part)} className="p-1.5 rounded-md text-red-600 hover:bg-red-50">
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>
              </div>
            ))}
            {!parts.loading && parts.data.length === 0 && (
              <div className="p-8 text-center text-sm text-[var(--muted-foreground)]">Belum ada part.</div>
            )}
          </div>
        </section>

        <section className="bg-[var(--card)] border border-[var(--border)] rounded-xl p-4 space-y-4">
          <div className="grid md:grid-cols-3 gap-3">
            <Field label="Nama part">
              <input value={form.partName} onChange={(e) => setForm((current) => ({ ...current, partName: e.target.value }))} className="input" />
            </Field>
            <Field label="Kode part">
              <input value={form.partCode} onChange={(e) => setForm((current) => ({ ...current, partCode: e.target.value }))} className="input" />
            </Field>
            <Field label="Vendor">
              <input value={form.vendor} onChange={(e) => setForm((current) => ({ ...current, vendor: e.target.value }))} className="input" />
            </Field>
          </div>

          <div className="flex items-center justify-between">
            <div>
              <h3 className="text-sm">Dimensi</h3>
              <p className="text-xs text-[var(--muted-foreground)] mt-0.5">
                Thickness disimpan sebagai tampak samping dengan kind width/length sesuai orientasi part.
              </p>
            </div>
            <button
              onClick={() => setForm((current) => ({ ...current, dimensions: [...current.dimensions, emptyDimension()] }))}
              className="inline-flex items-center gap-2 px-3 py-1.5 rounded-lg bg-blue-600 text-white text-xs"
            >
              <Plus className="w-3.5 h-3.5" /> Tambah dimensi
            </button>
          </div>

          <div className="space-y-3">
            {form.dimensions.map((dimension, index) => (
              <div key={dimension.id} className="rounded-lg border border-[var(--border)] p-3 space-y-3">
                <div className="grid md:grid-cols-[1fr_150px_150px_80px] gap-2">
                  <input value={dimension.name} onChange={(e) => updateDimension(index, { name: e.target.value })} placeholder="Nama dimensi" className="input" />
                  <select value={dimension.kind} onChange={(e) => updateDimension(index, { kind: e.target.value as DimensionKind })} className="input">
                    {KIND_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
                  </select>
                  <select value={dimension.view} onChange={(e) => updateDimension(index, { view: e.target.value as DimensionView })} className="input">
                    {VIEW_OPTIONS.map((option) => <option key={option.value} value={option.value}>{option.label}</option>)}
                  </select>
                  <input value={dimension.unit} onChange={(e) => updateDimension(index, { unit: e.target.value })} className="input" />
                </div>
                <div className="grid md:grid-cols-[1fr_1fr_1fr_auto] gap-2">
                  <input type="number" step="0.001" value={dimension.nominal} onChange={(e) => updateDimension(index, { nominal: Number(e.target.value) })} placeholder="Nominal" className="input" />
                  <input type="number" step="0.001" value={dimension.lowerLimit} onChange={(e) => updateDimension(index, { lowerLimit: Number(e.target.value) })} placeholder="Lower" className="input" />
                  <input type="number" step="0.001" value={dimension.upperLimit} onChange={(e) => updateDimension(index, { upperLimit: Number(e.target.value) })} placeholder="Upper" className="input" />
                  <button onClick={() => removeDimension(index)} className="inline-flex items-center justify-center gap-1 px-3 py-2 rounded-lg text-red-600 border border-red-200 hover:bg-red-50 text-xs">
                    <XCircle className="w-4 h-4" /> Hapus
                  </button>
                </div>
                <div className="text-[11px] text-[var(--muted-foreground)]">
                  {KIND_OPTIONS.find((option) => option.value === dimension.kind)?.note}
                </div>
              </div>
            ))}
          </div>

          <button disabled={saving} onClick={() => void save()} className="inline-flex items-center gap-2 px-4 py-2 rounded-lg bg-blue-600 text-white text-sm disabled:opacity-50">
            <Save className="w-4 h-4" /> {editingId ? 'Simpan perubahan' : 'Buat part'}
          </button>
        </section>
      </div>
    </div>
  );
}

function Field({ label, children }: { label: string; children: ReactNode }) {
  return (
    <label className="space-y-1 text-sm">
      <span className="text-xs text-[var(--muted-foreground)]">{label}</span>
      {children}
    </label>
  );
}

function Notice({ text }: { text: string }) {
  return <div className="bg-red-50 border border-red-200 text-red-700 rounded-xl p-3 text-sm">{text}</div>;
}
