// Frontend/src/lib/components/RequireAuth.svelte
<script lang="ts">
  import type { Snippet } from 'svelte';
  import { navigate } from 'svelte-routing';
  import { auth } from '$lib/stores/auth.svelte';

  let { children }: { children: Snippet } = $props();

  $effect(() => {
    if (auth.status === 'unauthenticated') {
      navigate('/login', { replace: true });
    }
  });
</script>

{#if auth.status === 'loading'}
  <div class="flex h-screen items-center justify-center bg-[var(--background)] text-[var(--muted-foreground)] text-sm">
    Memuat sesi...
  </div>
{:else if auth.status === 'authenticated'}
  {@render children()}
{/if}

// Frontend/src/app/components/RequireAuth.tsx
import { Navigate, Outlet } from 'react-router';
import { useAuth } from '../context/AuthContext';

export function RequireAuth() {
  const { status } = useAuth();

  if (status === 'loading') {
    return (
      <div className="flex h-screen items-center justify-center bg-[var(--background)] text-[var(--muted-foreground)] text-sm">
        Memuat sesi...
      </div>
    );
  }

  if (status === 'unauthenticated') {
    return <Navigate to="/login" replace />;
  }

  return <Outlet />;
}
